import React from "react";
import { Text, View, StyleSheet } from "@react-pdf/renderer";
const styles = StyleSheet.create({
  pageNumber: {
    position: "absolute",
    fontSize: 12,
    bottom: 20,
    left: 0,
    right: 0,
    textAlign: "center",
    color: "grey",
  },
  footer: {
    position: "absolute",
    fontSize: 12,
    bottom: 40,
    left: 0,
    right: 0,
    marginRight: 25,
    marginLeft: 25,
  },
  footerView: {
    display: "flex",
    flexDirection: "row",
    flexWrap: "wrap",

    fontSize: "10px",
  },
  footerViewItem: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    fontWeight: "bold",
    color: "black",
  },
  commonMarginBottom: {
    marginBottom: "5px",
  },
});
const PdfFooter = () => {
  return (
    <>
      <View fixed style={styles.footer}>
        <View style={styles.footerView}>
          <View style={styles.footerViewItem}>
            <Text style={styles.commonMarginBottom}>
              Signature of Recipient:
            </Text>
            <Text style={styles.commonMarginBottom}>Name:</Text>
            <Text style={styles.commonMarginBottom}>Designation:</Text>
          </View>
          <View style={[styles.footerViewItem, { marginLeft: "140px" }]}>
            <Text style={styles.commonMarginBottom}>
              Signature of Issuing Officer:
            </Text>
            <Text style={styles.commonMarginBottom}>Name:</Text>
            <Text style={styles.commonMarginBottom}>Designation:</Text>
          </View>
        </View>
        <View>
          <Text
            style={{
              fontStyle: "italic",
              fontSize: "10px",
            }}
          >
            Note- This Issue Voucher is generated by DVDMS, so kindly receive
          </Text>
        </View>
      </View>
      <Text
        fixed
        style={styles.pageNumber}
        render={({ pageNumber, totalPages }) => `${pageNumber} / ${totalPages}`}
      />
    </>
  );
};

export default React.memo(PdfFooter);
