
export const LOGIN = "LOGIN";
export const LOGIN_RESPONSE = "LOGIN_RESPONSE";
export const LOGOUT = "LOGOUT";
export const LOGOUT_RESPONSE = "LOGOUT_RESPONSE";
export const FORGOT_PASSWORD = "FORGOT_PASSWORD";
export const FORGOT_PASSWORD_RESPONSE = "FORGOT_PASSWORD_RESPONSE";
export const RESET_PASSWORD = "RESET_PASSWORD";
export const RESET_PASSWORD_RESPONSE = "RESET_PASSWORD_RESPONSE";
export const CLEAR_FORGOT_PASSWORD_RESPONSE = "CLEAR_FORGOT_PASSWORD_RESPONSE";
export const CHANGE_PASSWORD = "CHANGE_PASSWORD";
export const CHANGE_PASSWORD_RESPONSE = "CHANGE_PASSWORD_RESPONSE";

export const SET_LOGIN_RESPONSE  = "SET_LOGIN_RESPONSE"
