export const EDIT_USER = "EDIT_USER";
export const EDIT_USER_RESPONSE = "EDIT_USER_RESPONSE";

export const DELETE_USER = "DELETE_USER";
export const DELETE_USER_RESPONSE = "DELETE_USER_RESPONSE";

export const GET_USER_LIST = "GET_USER_LIST";
export const GET_USER_LIST_RESPONSE = "GET_USER_LIST_RESPONSE";

// export const GET_DRUG_LIST

// POST
export const CREATE_USER = "CREATE_USER";
export const CREATE_USER_RESPONSE = "CREATE_USER_RESPONSE";

export const EDIT_CERTIFICATE = "EDIT_CERTIFICATE";
export const EDIT_CERTIFICATE_RESPONSE = "EDIT_CERTIFICATE_RESPONSE";

export const FIND_CERTIFICATE_BY_ID = "FIND_CERTIFICATE_BY_ID";
export const FIND_CERTIFICATE__BY_ID_RESPONSE = "FIND_CERTIFICATE__BY_ID_RESPONSE";

export const DELETE_CERTIFICATE = "DELETE_CERTIFICATE";
export const DELETE_CERTIFICATE_RESPONSE = "DELETE_CERTIFICATE_RESPONSE";

export const GET_CERTIFICATE_LIST = "GET_CERTIFICATE_LIST";
export const GET_CERTIFICATE_LIST_RESPONSE = "GET_CERTIFICATE_LIST_RESPONSE";
export const CREATE_CERTIFICATE = "CREATE_CERTIFICATE";
export const CREATE_CERTIFICATE_RESPONSE = "CREATE_CERTIFICATE_RESPONSE";

export const FIND_CERTIFICATE_BY_EMAIL = "FIND_CERTIFICATE_BY_EMAIL";
export const FIND_CERTIFICATE__BY_EMAIL_RESPONSE = "FIND_CERTIFICATE__BY_EMAIL_RESPONSE";


//product store actions
export const EDIT_PRODUCT = "EDIT_PRODUCT";
export const EDIT_PRODUCT_RESPONSE = "EDIT_PRODUCT_RESPONSE";

export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const DELETE_PRODUCT_RESPONSE = "DELETE_PRODUCT_RESPONSE";

export const GET_PRODUCT_LIST = "GET_PRODUCT_LIST";
export const GET_PRODUCT_LIST_RESPONSE = "GET_PRODUCT_LIST_RESPONSE";

export const CREATE_PRODUCT = "CREATE_PRODUCT";
export const CREATE_PRODUCT_RESPONSE = "CREATE_PRODUCT_RESPONSE";

export const UPLOAD_IMAGE_PRODUCT = "UPLOAD_IMAGE_PRODUCT";
export const UPLOAD_IMAGE_PRODUCT_RESPONSE = "UPLOAD_IMAGE_PRODUCT_RESPONSE";

export const GET_IMAGE_PRODUCT = "GET_IMAGE_PRODUCT";
export const GET_IMAGE_PRODUCT_RESPONSE = "GET_IMAGE_PRODUCT_RESPONSE";

